### ISSUE TITLE
Crash on opening the timer screen

### ISSUE THREAD

**Issue by Asriel108** [FJuergen/lernhilfe#17]
0.5 Seconds after I open the timer screen the app closes/minimize itself. The other screens seem to work fine.

Honor 8
Android 7.0

**Comment by FJuergen** [comment]
Should be fixed in the latest release, though i only have a virtual device to test older android versions so there could be issues based on specific hardware that im not able to predict.

**Comment by Asriel108** [comment]
Tried the new build, but still crashes :/
